name: deploy

on:
  release:
    types: [created]

jobs:
  deploy-cancel-auto-zoom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '20.x'
    
      - run: yarn

      - run: yarn build

      - name: Publish package to NPM
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
